# bbrx config.yml for my Little Cat battlebot

bindings:
# servo channel 1
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_LY
  min: -512
  max: 511
  pin: 12

# servo channel 2 (normal mode, when the dual esc is mixed - both channels controlled by one stick)
# - action: BB_ACTION_SERVO
#   event: BB_EVENT_ANALOG_LX
#   min: 511
#   max: -512
#   pin: 14

# servo channel 2 (katamari mode, when the dual esc is NOT mixed - left motor = left stick)
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_RY
  min: -512
  max: 511
  pin: 14

# weapon control
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_THROTTLE
  min: 0
  max: 1023
  servo_pwm_mid: 1000
  pin: 4

# speed control
- action: BB_ACTION_SPEED_UP
  event: BB_EVENT_BTN_B
  min: 0
  max: 1

- action: BB_ACTION_SPEED_UP
  event: BB_EVENT_DPAD_UP
  min: 0
  max: 1

- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_BTN_X
  min: 0
  max: 1

- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_DPAD_DOWN
  min: 0
  max: 1

# break
- action: BB_ACTION_BRAKE
  event: BB_EVENT_BTN_A
  min: 0
  max: 1
